services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend

  agent-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["python", "-m", "app.agents.agents_worker", "start"]
    env_file:
      - ./backend/.env
    depends_on:
      - backend

  # supabase:
  #   image: supabase/postgres:15.1.0.82
  #   restart: always
  #   ports:
  #     - "5432:5432"